# Generated by Django 4.1.3 on 2022-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blognews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                ("content", models.TextField()),
                ("post_by", models.EmailField(max_length=254)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
