# Generated by Django 4.1.3 on 2022-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blognews",
            name="image",
            field=models.ImageField(upload_to="news"),
        ),
    ]
